<?php

function ff24Crea($dd)
{
    $sql = '
CREATE TABLE `ff24` (
  `id` int(11) DEFAULT NULL,
  `stabile_id` int(11) NULL,
  `stabile_uuid` varchar(36) NULL,
    `mese` int(2) DEFAULT NULL,
    `anno` int(2) DEFAULT NULL,
    `banca_f24` varchar(50) DEFAULT NULL,
    `agenzia` varchar(50) DEFAULT NULL,
    `dt_pagamento` datetime DEFAULT NULL,
    `cod_tributo_1` varchar(4) DEFAULT NULL,
    `cod_tributo_2` varchar(4) DEFAULT NULL,
    `cod_tributo_3` varchar(4) DEFAULT NULL,
    `cod_tributo_4` varchar(4) DEFAULT NULL,
    `cod_tributo_5` varchar(4) DEFAULT NULL,
    `cod_tributo_6` varchar(4) DEFAULT NULL,
    `rateiz_1` varchar(5) DEFAULT NULL,
    `rateiz_2` varchar(5) DEFAULT NULL,
    `rateiz_3` varchar(5) DEFAULT NULL,
    `rateiz_4` varchar(5) DEFAULT NULL,
    `rateiz_5` varchar(5) DEFAULT NULL,
    `rateiz_6` varchar(5) DEFAULT NULL,
    `anno_1` int(2) DEFAULT NULL,
    `anno_2` int(2) DEFAULT NULL,
    `anno_3` int(2) DEFAULT NULL,
    `anno_4` int(2) DEFAULT NULL,
    `anno_5` int(2) DEFAULT NULL,
    `anno_6` int(2) DEFAULT NULL,
    `importo_tributo_deb_1` decimal(10,2) DEFAULT NULL,
    `importo_tributo_deb_2` decimal(10,2) DEFAULT NULL,
    `importo_tributo_deb_3` decimal(10,2) DEFAULT NULL,
    `importo_tributo_deb_4` decimal(10,2) DEFAULT NULL,
    `importo_tributo_deb_5` decimal(10,2) DEFAULT NULL,
    `importo_tributo_deb_6` decimal(10,2) DEFAULT NULL,
    `importo_tributo_cre_1` decimal(10,2) DEFAULT NULL,
    `importo_tributo_cre_2` decimal(10,2) DEFAULT NULL,
    `importo_tributo_cre_3` decimal(10,2) DEFAULT NULL,
    `importo_tributo_cre_4` decimal(10,2) DEFAULT NULL,
    `importo_tributo_cre_5` decimal(10,2) DEFAULT NULL,
    `importo_tributo_cre_6` decimal(10,2) DEFAULT NULL,
    `sede_inps_1` varchar(4) DEFAULT NULL,
    `sede_inps_2` varchar(4) DEFAULT NULL,
    `sede_inps_3` varchar(4) DEFAULT NULL,
    `sede_inps_4` varchar(4) DEFAULT NULL,
    `caus_contrib_1` varchar(4) DEFAULT NULL,
    `caus_contrib_2` varchar(4) DEFAULT NULL,
    `caus_contrib_3` varchar(4) DEFAULT NULL,
    `caus_contrib_4` varchar(4) DEFAULT NULL,
    `matricola_1` varchar(18) DEFAULT NULL,
    `matricola_2` varchar(18) DEFAULT NULL,
    `matricola_3` varchar(18) DEFAULT NULL,
    `matricola_4` varchar(18) DEFAULT NULL,
    `dal_1` varchar(7) DEFAULT NULL,
    `dal_2` varchar(7) DEFAULT NULL,
    `dal_3` varchar(7) DEFAULT NULL,
    `dal_4` varchar(7) DEFAULT NULL,
    `al_1` varchar(7) DEFAULT NULL,
    `al_2` varchar(7) DEFAULT NULL,
    `al_3` varchar(7) DEFAULT NULL,
    `al_4` varchar(7) DEFAULT NULL,
    `importo_contrib_deb_1` decimal(10,2) DEFAULT NULL,
    `importo_contrib_deb_2` decimal(10,2) DEFAULT NULL,
    `importo_contrib_deb_3` decimal(10,2) DEFAULT NULL,
    `importo_contrib_deb_4` decimal(10,2) DEFAULT NULL,
    `importo_contrib_cre_1` decimal(10,2) DEFAULT NULL,
    `importo_contrib_cre_2` decimal(10,2) DEFAULT NULL,
    `importo_contrib_cre_3` decimal(10,2) DEFAULT NULL,
    `importo_contrib_cre_4` decimal(10,2) DEFAULT NULL,
    `cod_regione_1` varchar(2) DEFAULT NULL,
    `cod_regione_2` varchar(2) DEFAULT NULL,
    `cod_regione_3` varchar(2) DEFAULT NULL,
    `trib_regione_1` varchar(4) DEFAULT NULL,
    `trib_regione_2` varchar(4) DEFAULT NULL,
    `trib_regione_3` varchar(4) DEFAULT NULL,
    `rateiz_regione_1` varchar(5) DEFAULT NULL,
    `rateiz_regione_2` varchar(5) DEFAULT NULL,
    `rateiz_regione_3` varchar(5) DEFAULT NULL,
    `anno_regione_1` int(2) DEFAULT NULL,
    `anno_regione_2` int(2) DEFAULT NULL,
    `anno_regione_3` int(2) DEFAULT NULL,
    `importo_regione_deb_1` decimal(10,2) DEFAULT NULL,
    `importo_regione_deb_2` decimal(10,2) DEFAULT NULL,
    `importo_regione_deb_3` decimal(10,2) DEFAULT NULL,
    `importo_regione_cre_1` decimal(10,2) DEFAULT NULL,
    `importo_regione_cre_2` decimal(10,2) DEFAULT NULL,
    `importo_regione_cre_3` decimal(10,2) DEFAULT NULL,
    `ici_comune` varchar(4) DEFAULT NULL,
    `ici_rav` varchar(1) DEFAULT NULL,
    `ici_i_var` varchar(1) DEFAULT NULL,
    `ici_acc` varchar(1) DEFAULT NULL,
    `ici_sal` varchar(1) DEFAULT NULL,
    `ici_nimm` int(2) DEFAULT NULL,
    `ici_tributo` varchar(4) DEFAULT NULL,
    `ici_rateazione` varchar(5) DEFAULT NULL,
    `ici_anno` int(2) DEFAULT NULL,
    `ici_importo_deb` decimal(10,2) DEFAULT NULL,
    `ici_importo_cre` decimal(10,2) DEFAULT NULL,
    `sede_inail_1` varchar(5) DEFAULT NULL,
    `sede_inail_2` varchar(5) DEFAULT NULL,
    `sede_inail_3` varchar(5) DEFAULT NULL,
    `op_cod_1` varchar(8) DEFAULT NULL,
    `op_cod_2` varchar(8) DEFAULT NULL,
    `op_cod_3` varchar(8) DEFAULT NULL,
    `s_cod_1` varchar(2) DEFAULT NULL,
    `s_cod_2` varchar(2) DEFAULT NULL,
    `s_cod_3` varchar(2) DEFAULT NULL,
    `num_riferimento_1` varchar(9) DEFAULT NULL,
    `num_riferimento_2` varchar(9) DEFAULT NULL,
    `num_riferimento_3` varchar(9) DEFAULT NULL,
    `causale_1` varchar(2) DEFAULT NULL,
    `causale_2` varchar(2) DEFAULT NULL,
    `causale_3` varchar(2) DEFAULT NULL,
    `importo_inail_deb_1` decimal(10,2) DEFAULT NULL,
    `importo_inail_deb_2` decimal(10,2) DEFAULT NULL,
    `importo_inail_deb_3` decimal(10,2) DEFAULT NULL,
    `importo_inail_cre_1` decimal(10,2) DEFAULT NULL,
    `importo_inail_cre_2` decimal(10,2) DEFAULT NULL,
    `importo_inail_cre_3` decimal(10,2) DEFAULT NULL,
    `totale_f24` decimal(10,2) DEFAULT NULL,
    `prov` varchar(5) DEFAULT NULL,
    `dt_versamento` varchar(10) DEFAULT NULL,
    `azienda` varchar(5) DEFAULT NULL,
    `cab_sportello` varchar(5) DEFAULT NULL,
    `addeb_cc_n` varchar(20) DEFAULT NULL,
    `addeb_abi` varchar(5) DEFAULT NULL,
    `addeb_cab` varchar(5) DEFAULT NULL,
    `autom_manuale` varchar(12) DEFAULT NULL,
    `rif_f24_mio` int(4) DEFAULT NULL,
    `ici_comune2` varchar(4) DEFAULT NULL,
    `ici_rav2` varchar(1) DEFAULT NULL,
    `ici_i_var2` varchar(1) DEFAULT NULL,
    `ici_acc2` varchar(1) DEFAULT NULL,
    `ici_sal2` varchar(1) DEFAULT NULL,
    `ici_nimm2` int(2) DEFAULT NULL,
    `ici_tributo2` varchar(4) DEFAULT NULL,
    `ici_rateazione2` varchar(5) DEFAULT NULL,
    `ici_anno2` int(2) DEFAULT NULL,
    `ici_importo_deb2` decimal(10,2) DEFAULT NULL,
    `ici_importo_cre2` decimal(10,2) DEFAULT NULL,
    `selez_f24` varchar(2) DEFAULT NULL,
    `addeb_iban` varchar(27) DEFAULT NULL,
    `nome_file_telematico` varchar(100) DEFAULT NULL,
    `etic_axivar` varchar(50) DEFAULT NULL,
    `di_cui_interessi` decimal(10,2) DEFAULT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

    ALTER TABLE `f24` ADD PRIMARY KEY (`id`),  ADD UNIQUE KEY `uuid` (`uuid`);
    ALTER TABLE `f24` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
    ';

    $dd->query($sql);
    echo '<br/>'.$sql.'<br/>';
}

function ff24Importa($ds, $dd)
{
    $table = 'f24';
    $columns = [
        'id_stabile (stabile_id)',
        //`stabile_uuid` varchar(36) NULL,
          'mese',
          'anno',
          'banca_f24',
          'agenzia',
          'dt_pagamento',
          'cod_tributo_1',
          'cod_tributo_2',
          'cod_tributo_3',
          'cod_tributo_4',
          'cod_tributo_5',
          'cod_tributo_6',
          'rateiz_1',
          'rateiz_2',
          'rateiz_3',
          'rateiz_4',
          'rateiz_5',
          'rateiz_6',
          'anno_1',
          'anno_2',
          'anno_3',
          'anno_4',
          'anno_5',
          'anno_6',
          'importo_tributo_deb_1',
          'importo_tributo_deb_2',
          'importo_tributo_deb_3',
          'importo_tributo_deb_4',
          'importo_tributo_deb_5',
          'importo_tributo_deb_6',
          'importo_tributo_cre_1',
          'importo_tributo_cre_2',
          'importo_tributo_cre_3',
          'importo_tributo_cre_4',
          'importo_tributo_cre_5',
          'importo_tributo_cre_6',
          'sede_inps_1',
          'sede_inps_2',
          'sede_inps_3',
          'sede_inps_4',
          'caus_contrib_1',
          'caus_contrib_2',
          'caus_contrib_3',
          'caus_contrib_4',
          'matricola_1',
          'matricola_2',
          'matricola_3',
          'matricola_4',
          'dal_1',
          'dal_2',
          'dal_3',
          'dal_4',
          'al_1',
          'al_2',
          'al_3',
          'al_4',
          'importo_contrib_deb_1',
          'importo_contrib_deb_2',
          'importo_contrib_deb_3',
          'importo_contrib_deb_4',
          'importo_contrib_cre_1',
          'importo_contrib_cre_2',
          'importo_contrib_cre_3',
          'importo_contrib_cre_4',
          'cod_regione_1',
          'cod_regione_2',
          'cod_regione_3',
          'trib_regione_1',
          'trib_regione_2',
          'trib_regione_3',
          'rateiz_regione_1',
          'rateiz_regione_2',
          'rateiz_regione_3',
          'anno_regione_1',
          'anno_regione_2',
          'anno_regione_3',
          'importo_regione_deb_1',
          'importo_regione_deb_2',
          'importo_regione_deb_3',
          'importo_regione_cre_1',
          'importo_regione_cre_2',
          'importo_regione_cre_3',
          'ici_comune',
          'ici_rav',
          'ici_i_var',
          'ici_acc',
          'ici_sal',
          'ici_nimm',
          'ici_tributo',
          'ici_rateazione',
          'ici_anno',
          'ici_importo_deb',
          'ici_importo_cre',
          'sede_inail_1',
          'sede_inail_2',
          'sede_inail_3',
          'op_cod_1',
          'op_cod_2',
          'op_cod_3',
          's_cod_1',
          's_cod_2',
          's_cod_3',
          'num_riferimento_1',
          'num_riferimento_2',
          'num_riferimento_3',
          'causale_1',
          'causale_2',
          'causale_3',
          'importo_inail_deb_1',
          'importo_inail_deb_2',
          'importo_inail_deb_3',
          'importo_inail_cre_1',
          'importo_inail_cre_2',
          'importo_inail_cre_3',
          'totale_f24',
          'prov',
          'dt_versamento',
          'azienda',
          'cab_sportello',
          'addeb_cc_n',
          'addeb_abi',
          'addeb_cab',
          'autom_manuale',
          'rif_f24_mio',
          'ici_comune2',
          'ici_rav2',
          'ici_i_var2',
          'ici_acc2',
          'ici_sal2',
          'ici_nimm2',
          'ici_tributo2',
          'ici_rateazione2',
          'ici_anno2',
          'ici_importo_deb2',
          'ici_importo_cre2',
          'selez_f24',
          'addeb_iban',
          'nome_file_telematico',
          'etic_axivar',
          'di_cui_interessi',
        ];

    $ff24 = $ds->select($table, $columns);

    if (!empty($ff24)) {
        echo 'ff24 NOT empty';
        foreach ($ff24 as &$f24) {
            echo '<br/>';
            print_r($f24);
            echo 'stabile_id='.$f24['stabile_id'].'<br/>';
            $stabile_uuid = stabile_uuid($dd, $f24['stabile_id']);
            $f24['stabile_uuid'] = $stabile_uuid;
            $dd->insert('ff24', $f24);
        }
    }
}
